five_letter_words = [
    "apple", "angel", "badge", "baker", "beard", "beast", "bison", "black", "blink", "brick",
    "cabin", "cagey", "candy", "cease", "chase", "cheer", "climb", "clock", "cloud", "crazy",
    "dance", "dealt", "demon", "douse", "dream", "eager", "eagle", "elbow", "empty", "enemy",
    "fable", "faith", "flame", "flask", "flood", "forge", "frail", "frost", "giant", "glory",
    "grape", "green", "guard", "guilt", "habit", "happy", "heart", "honor", "house", "hurry",
    "ideal", "image", "ivory", "jolly", "joint", "jumpy" "knife", "labor", "latch",
    "laugh", "liver", "loose", "lucky", "magic", "maple", "mercy", "merry", "music", "noble",
    "oasis", "ocean", "olive", "opera", "order", "panda", "peace", "piano", "pride", "quiet",
    "radio", "rebel", "robin", "sable", "saint", "scale", "shady", "sheep", "shine", "silly",
    "sleek", "smart", "smile", "snake", "solid", "spike", "spine", "sugar", "swift", "table",
    "tiger", "tooth", "trace", "trick", "twist", "uncle", "union", "vivid", "voice", "waste",
    "water", "whale", "wheel", "widen", "wrist", "young", "zebra", "zesty", "abide", "acute",
    "adore", "agree", "alert", "amaze", "angel", "antic", "asset", "awake", "beard", "belly",
    "bison", "blast", "bliss", "brain", "brave", "broom", "bunny", "candy", "cease", "charm",
    "chase", "cheer", "chief", "clash", "clear", "climb", "close", "clown", "crazy", "crisp",
    "dance", "dealt", "debut", "delve", "demon", "dozen", "dream", "early", "eager", "eagle",
    "elbow", "empty", "enemy", "equal", "error", "fable", "faith", "flame", "flash", "flock",
    "flora", "forge", "frail", "frost", "giant", "glory", "grape", "green", "guard", "guilt",
    "habit", "happy", "heart", "honor", "house", "hurry", "ideal", "image", "ivory", "jolly",
    "joint", "jumpy", "knife", "labor", "latch", "laugh", "liver", "loose", "lucky",
    "magic", "maple", "mercy", "merry", "music", "noble", "oasis", "ocean", "olive", "opera",
    "order", "panda", "peace", "piano", "pride", "quiet", "radio", "rebel", "robin", "sable",
    "saint", "scale", "shady", "sheep", "shine", "silly", "sleek", "smart", "smile", "snake",
    "solid", "spike", "spine", "sugar", "swift", "table", "tiger", "tooth", "trace", "trick",
    "twist", "uncle", "union", "vivid", "voice", "waste", "water", "whale", "wheel", "widen",
    "wrist", "young", "zebra", "zesty", "abide", "acute", "adore", "agree", "alert", "amaze",
    "angel", "antic", "asset", "awake", "beard", "belly", "bison", "blast", "bliss", "brain",
    "brave", "broom", "bunny", "candy", "cease", "charm", "chase", "cheer", "chief", "clash",
    "clear", "climb", "close", "clown", "crazy", "crisp", "dance", "dealt", "debut", "delve",
    "demon", "dozen", "dream", "early", "eager", "eagle", "elbow", "empty", "enemy", "equal",
    "error", "fable", "faith", "flame", "flash", "speed", "sleep"]